
var agentTimerId;var reiTimerId;var cancelTimerId=null;function agent3s(ans){var anses=[];var appname='';if(ans.endsWith(":")){ans=ans.replace(/:/,'');}else{appname='agent3s';}
var numpush=getNumpush(ans);anses=ans.split(',');var iam='9999';elemIam=document.getElementById("iam");if(elemIam!=null){iam=elemIam.textContent;}
var vlu=iam+':'+ans+':'+appname;jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjsns.php',data:{'func':'getSeatsAction','argument':vlu},success:function(content){var tst=[];tst=content.split(':');suu=tst[0];var vew=[];var answs=[];var dataes={};if(tst[1].length>0){var vex=tst[1].split(',');for(var i=0;i<vex.length;++i){var wxw=vex[i].split('|');answs.push(wxw[2]);dataes[wxw[2]]=vex[i];}
for(var i=0;i<1;++i){if(answs.indexOf(anses[i])<0){vew.push('-');}else{vew.push(dataes[anses[i]]);}}}
for(var i=0;i<1;++i){target=document.getElementById("agentsts");targetQ=document.getElementById("spekksts");if(target===null){continue;}
if(i<anses.length){var call='',spek='';if(answs.indexOf(anses[i])<0){if(target==null){;}else{target.innerHTML='<img src="'+'https://bden.siptables.net/'+'images/riseki.png">';}
if(targetQ==null){;}else{targetQ.innerHTML='';}}else{var wew=vew[i].split('|');if(wew[16].length>0){downloadFile2(wew[15],wew[16]);clearInterval(reiTimerId);clearInterval(agentTimerId);excIam(9999);setTimeout(agent3s,1000,ans);}
if(wew[0]==0){call='<img src="'+'https://bden.siptables.net/'+'images/riseki.png" title="'+wew[2]+'">';}else if(wew[0]==1){call='<div class="aglcallup"><span tabindex="0" class="inn" style="--callup: url(images/'+numpush+'/callup.jpg); --callup2: url(images/'+numpush+'/callup2.jpg);" onclick="if(!amI9999()) { return false; } (function(){ var kintama = \'\'; var foo = function(){ var ppp = \'\'; $.ajax({ type: \'post\', url: \'https://bden.siptables.net/'+'calledbyjsns.php\', data: {\'func\' : \'getAskerMustBe\' }, async: false }).done(function(content) { ppp = content; }); kintama = ppp; }; foo(); excIam(kintama); startCallRegister('+ans+'); location.href=`bden:numpush+'+ans+':6:'+wew[9]+'+'+'${kintama}`; })(); window.agentTimerId = setInterval(agent3s,3000,\''+ans+'\'); setTimeout(agent3s,0,\''+ans+'\'); window.reiTimerId = setInterval(doReInvite,1000 * 90,\''+ans+'\'); window.cancelTimerId = setTimeout(doInvite487,1000 * 30,\''+ans+'\');"><img src="'+'https://bden.siptables.net/'+'images/'+numpush+'/numpush.png"></span></div>';}else if(wew[0]==2){if(suu==(-1)){call='<div class="aglcallmissed"><img src="'+'https://bden.siptables.net/'+'images/ring/ringing.gif"></div>';}
else{call='<div class="aglcallmissed"><span tabindex="0" class="inn" style="--missed: url(images/'+numpush+'/missed.jpg); --missed2: url(images/'+numpush+'/missed2.jpg);" onclick="stopCallRegister('+ans+'); location.href=\'bden:crstop\'; clearTimeout(cancelTimerId); cancelTimerId = null;"><img src="'+'https://bden.siptables.net/'+'images/ring/ringing.gif"></span></div>';}}else if(wew[0]==3){if(cancelTimerId!=null){clearTimeout(cancelTimerId);cancelTimerId=null;}
if(suu==(-1)){call='<div class="aglcalldown"><img src="'+'https://bden.siptables.net/'+'images/'+numpush+'/calling.png"></div>';}
else{call='<div class="aglcalldown"><span tabindex="0" class="inn" style="--calldown: url(images/'+numpush+'/calldown.jpg); --calldown2: url(images/'+numpush+'/calldown2.jpg);" onclick="stopCallRegister('+ans+'); location.href=\'bden:crstop\'"><img src="'+'https://bden.siptables.net/'+'images/'+numpush+'/calling.png"></span></div>';}}else if(wew[0]==11){call='<img src="'+'https://bden.siptables.net/'+'images/'+numpush+'/numpush.png">';}else if(wew[0]==12){call='<img src="'+'https://bden.siptables.net/'+'images/ring/ringing.gif">';}else if(wew[0]==13){call='<img src="'+'https://bden.siptables.net/'+'images/'+numpush+'/calling.png">';}
if(target!==null){target.innerHTML=call;}
if(wew[0]==3){spek='通話中';}else if(wew[0]==1){spek=((wew[0]==0)?"15分超":((wew[4]==0)?"在席保証なし":((wew[4]==1)?"離席":((wew[4]==2)?"トイレ":((wew[4]==3)?"在席":((wew[4]==4)?"投票":wew[4]))))));}else{spek=((wew[0]==0)?"15分超":((wew[4]==0)?"在席保証なし":((wew[4]==1)?"離席":((wew[4]==2)?"トイレ":((wew[4]==3)?"在席":((wew[4]==4)?"投票":wew[4]))))));}
if(targetQ!==null){targetQ.innerHTML=spek;}}}else{if(target==null){;}else{target.innerHTML='<img src="'+'https://bden.siptables.net/'+'images/riseki.png">';}
if(targetQ==null){;}else{targetQ.innerHTML='';}}}}});}
function excIam(sipuri){document.getElementById("iam").textContent=sipuri;}
function amI9999(){return(document.getElementById("iam").textContent<9999)?false:true;}
function doMySyslog(mes){var vlu=mes;jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjs.php',data:{'func':'doMySyslog','argument':vlu},success:function(content){}});}
function getNumpush(ans){var kintama='';var foo=function(){var ppp='';jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjs.php',data:{'func':'getNumpush','argument':ans},async:false,success:function(content){ppp=content;}});kintama=ppp;};foo();return kintama;}
async function startCallRegister(ans){var localip='';var contactip='';if(localip.length>0){contactip=localip;}else{const res=await fetch('https://api.ipify.org/?format=json');const data=await res.json();contactip=data.ip;}
var vlu=ans+','+document.getElementById("iam").textContent+','+contactip;jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjsns.php',data:{'func':'startCallRegister','argument':vlu},async:false,success:function(content){}});}
function stopCallRegister(ans){var vlu=ans+','+document.getElementById("iam").textContent;jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjsns.php',data:{'func':'stopCallRegister','argument':vlu},success:function(content){}});}
function doReInvite(ans){var vlu=ans+','+document.getElementById("iam").textContent;jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjsns.php',data:{'func':'doReInvite','argument':vlu},success:function(content){}});}
function doInvite487(ans){var vlu=ans+','+document.getElementById("iam").textContent;jQuery.ajax({type:'post',url:'https://bden.siptables.net/'+'calledbyjsns.php',data:{'func':'doInvite487','argument':vlu},success:function(content){}});}
function downloadFile2(kaiji,content){const imageName=Math.random().toString(32).substring(2);var blob=new Blob([content.replace(/#/g,':').replace(/200 非開示は拒否.*$/,'200 XXXX').replace(/全て通す.*$/,'XXXX').replace(/プ情なし.*$/,'XXXX')],{"type":"text/csv"});var downLoadLink=document.createElement("a");downLoadLink.download=imageName+".txt";downLoadLink.href=window.URL.createObjectURL(blob);downLoadLink.dataset.downloadurl=["text/plain",downLoadLink.download,downLoadLink.href].join(":");downLoadLink.click();}